feat: Enable Hubble Relay in Cilium deployment via CAAPH
nutanix-cloud-native/cluster-api-runtime-extensions-nutanix pull request #899
Opened 2024-09-03 21:22 UTC by dlipovetsky

**What problem does this PR solve?**:
Relay is required for network visibility of a cluster as a whole. See https://docs.cilium.io/en/stable/gettingstarted/hubble_intro/.

**Which issue(s) this PR fixes**:
Fixes #

**How Has This Been Tested?**:

**Special notes for your reviewer**:

2024-09-03 21:50 UTC, faiq approved these changes

2024-09-04 08:58 UTC, jimmidyson approved these changes

2024-09-04 15:22 UTC, jimmidyson requested changes

2024-09-04 15:22 UTC, jimmidyson commented on charts/cluster-api-runtime-extensions-nutanix/templates/cni/cilium/manifests/helm-addon-installation.yaml
> +      relay: enabled
Ran locally and cilium install failed with (taken from Cilium HCP):

```
values don't meet the specifications of the schema(s) in the following chart(s):
cilium:
- hubble.relay: Invalid type. Expected: object, given: string
```
```suggestion
      relay:
        enabled: true
```

2024-09-05 08:25 UTC, jimmidyson commented
@dlipovetsky Please can you add a test to e2e to ensure the necessary hubble components are running? This will also help us know what to expect in-cluster when Hubble is enabled.

2024-09-05 11:56 UTC, jimmidyson commented
@dlipovetsky Force pushed after editing last commit message to pass gitlint.

2024-09-05 12:51 UTC, jimmidyson commented
Added e2e test in 56a583c7187cdb7390e233966a90fb3823d517c6 (while also taking the opportunity to tidy up "kube-system" consts).

2024-09-05 14:39 UTC, jimmidyson approved these changes

2024-09-05 14:45 UTC, mhrabovcin approved these changes

2024-09-05 14:45 UTC, merged